version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: subscripton
    container_name: subscripton
    ports:
      - "8005:80"
    volumes:
      - .:/var/www/html
    # depends_on:
    #   - db
    networks:
      - laravel

#   db:
#     image: mysql:5.7
#     container_name: mysql-laravel
#     environment:
#       MYSQL_ROOT_PASSWORD: my_secret_root_password
#       MYSQL_DATABASE: laravel_db
#       MYSQL_USER: laravel_user
#       MYSQL_PASSWORD: my_secret_laravel_password
#     ports:
#       - "3306:3306"
#     volumes:
#       - db_data:/var/lib/mysql
#     networks:
#       - laravel

networks:
  laravel:

volumes:
  db_data:
